# Generated by Django 5.2.7 on 2025-10-23 06:35

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_photo', models.ImageField(upload_to='category_photo/')),
                ('category_name', models.CharField(max_length=34, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('product_image', models.ImageField(upload_to='product_image/')),
                ('product_price', models.PositiveSmallIntegerField()),
                ('product_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('product_description', models.TextField()),
                ('product_type', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lalafo.category')),
            ],
        ),
    ]
